name: Linting Stage
on: [pull_request]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Settting Up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installing Node Dependencies
        run: pnpm install --frozen-lockfile

      - name: Dog is reviewing
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
